name: Deploy assets

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install s3deploy
        run: ./ci-install-s3deploy.sh
        env:
          S3DEPLOY_VERSION: 2.3.5
      - name: Deploy to S3
        run: ./s3deploy -bucket static.juev.org -public-access -region eu-west-2 -max-delete -1 -source public/
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
